# Generated by Django 4.1 on 2023-04-20 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PingpongJob',
            fields=[
                ('jobId', models.TextField(primary_key=True, serialize=False)),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('iteration', models.IntegerField()),
                ('data', models.TextField()),
            ],
        ),
    ]
